fos_rest:
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json }

  exception:
    enabled: true

  view:
    view_response_listener: 'force'
    formats:
      json: true